INSERT INTO medico (matricula, nombre, apellido, especialidad, observaciones) VALUES (155, "Alfredo", "Gutierrez", "Medicina Familiar", "No atiende PAMI");
INSERT INTO medico (matricula, nombre, apellido, especialidad, observaciones) VALUES (221, "Luisa", "Foseca", "Cardiología", null);
INSERT INTO medico (matricula, nombre, apellido, especialidad, observaciones) VALUES (226, "Frodo", "Bolson", "Pediatría", "Solamente turno tarde");
INSERT INTO medico (matricula, nombre, apellido, especialidad, observaciones) VALUES (332, "Jesus María", "Prates", "Cirugía", null);
INSERT INTO medico (matricula, nombre, apellido, especialidad, observaciones) VALUES (334, "Gandalf", "Meriadoc", "Infectología", null);
INSERT INTO medico (matricula, nombre, apellido, especialidad, observaciones) VALUES (449, "Ricardo", "Puchini", "Medicina Familiar", "medico clinico general");
INSERT INTO medico (matricula, nombre, apellido, especialidad, observaciones) VALUES (645, "Cacho", "Villa", "Oftamología", null);
INSERT INTO medico (matricula, nombre, apellido, especialidad, observaciones) VALUES (733, "Tatiana", "Brandigamo", "Pediatría", null);
INSERT INTO medico (matricula, nombre, apellido, especialidad, observaciones) VALUES (774, "Alfonso", "Chamorro", "Cardiología", null);
INSERT INTO medico (matricula, nombre, apellido, especialidad, observaciones) VALUES (888, "Pedro Pablo", "Chichanowski", "Urología", "Actualmente con licencia por covid");

INSERT INTO paciente (nss, nombre, apellido, domicilio, codigo_postal, telefono, nro_historial_clinico, observaciones) VALUES (32197, "Aewin", "Rohan", "Valinor 10001", 2366, "3274-232336", 675, null);
INSERT INTO paciente (nss, nombre, apellido, domicilio, codigo_postal, telefono, nro_historial_clinico, observaciones) VALUES (971649, "Glorfindel", "Arda", "Terminal esquina Avenida", 3360, "3755-447031", 778, "realizar PCR");
INSERT INTO paciente (nss, nombre, apellido, domicilio, codigo_postal, telefono, nro_historial_clinico, observaciones) VALUES (316619, "Karen Sophia", "Burgin", "Primeros Colonos y Junin", 3640, "3745-998877", 1236, null);
INSERT INTO paciente (nss, nombre, apellido, domicilio, codigo_postal, telefono, nro_historial_clinico, observaciones) VALUES (3648, "Gimli", "Moria", "Juan Manuel de Orquideas 335", 3363, "3755-866545", 1488, null);
INSERT INTO paciente (nss, nombre, apellido, domicilio, codigo_postal, telefono, nro_historial_clinico, observaciones) VALUES (87164, "Legolas", "Bosque Negro", "Krause y Villavieja", 3514, "3971-544444", 1498, "historial de cardiopatias");
INSERT INTO paciente (nss, nombre, apellido, domicilio, codigo_postal, telefono, nro_historial_clinico, observaciones) VALUES (254651, "Elrond", "Rivendell", "Balneario Campo Grande", 3350, "3764-421479", 1884, null);
INSERT INTO paciente (nss, nombre, apellido, domicilio, codigo_postal, telefono, nro_historial_clinico, observaciones) VALUES (369844, "Galadriel", "Lorien", "Bareiro 170", 2207, "3943-425561", 3212, null);
INSERT INTO paciente (nss, nombre, apellido, domicilio, codigo_postal, telefono, nro_historial_clinico, observaciones) VALUES (44946, "Josefina", "Pereira Dias", "Calle primera 201", 3363, "3755-587912", 4112, null);
INSERT INTO paciente (nss, nombre, apellido, domicilio, codigo_postal, telefono, nro_historial_clinico, observaciones) VALUES (654165, "Jose", "Villagran", "Arrayanes 1205", 3360, "3755-589478", 4551, null);

INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2021-11-1", 1, 2, 1884, 449);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2021-11-2", 1, 1, 1488, 226);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, observaciones, nro_historial_paciente, matricula_medico) VALUES ("2021-11-2", 2, 4, "Falta completar carnet de vacunacion", 1498, 733);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2021-11-3", 1, 2, 4551, 774);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama,  nro_historial_paciente, matricula_medico) VALUES ("2021-11-5", 4, 7, 4112, 645);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2021-11-15", 5, 9, 1236, 226);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2021-11-17", 5, 10, 675, 774);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2021-12-9", 3, 6, 778, 888);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, observaciones, nro_historial_paciente, matricula_medico) VALUES ("2021-12-11", 4, 8, "Solicitar electrocardiograma", 4112, 332);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2021-12-11", 2, 3, 3212, 774);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2021-12-18", 2, 4, 778, 334);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2021-12-22", 1, 1, 1488, 155);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-1-4", 9, 17, 1236, 645);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-1-11", 5, 9, 675, 226);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-1-12", 4, 8, 3212, 155);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-1-16", 8, 16, 1236, 226);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-1-24", 2, 3, 1488, 888);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-2-1", 8, 15, 3212, 334);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-2-14", 1, 2, 1884, 449);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-2-15", 7, 13, 4112, 888);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-3-2", 3, 5, 675, 155);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-3-7", 8, 12, 4551, 334);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-3-13", 3, 6, 1498, 645);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-3-16", 9, 18, 675, 155);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-3-19", 5, 9, 4112, 774);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, observaciones, nro_historial_paciente, matricula_medico) VALUES ("2022-3-22", 6, 11, "Cuenta con servicio integral de reabilitacion", 1498, 332);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-3-22", 3, 6, 1884, 332);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-3-22", 5, 10, 778, 449);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-3-23", 1, 1, 4112, 155);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-3-25", 3, 6, 1236, 226);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-3-29", 2, 4, 3212, 645);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-3-30", 9, 17, 4112, 155);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, observaciones, nro_historial_paciente, matricula_medico) VALUES ("2022-4-5", 6, 11, "Internacion por deshidratacion", 1488, 733);
INSERT INTO ingreso (fecha_ingreso, nro_habitacion, nro_cama, nro_historial_paciente, matricula_medico) VALUES ("2022-4-7", 7, 13, 4551, 774);


